//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Система_учёта_готовой_продукции_на_складе
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Cost_ed { get; set; }
        public Nullable<long> Count { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<decimal> CostAll 
        { get
            {
                return Cost_ed*Count;
            } 
        }
    }
}
